### ISSUE TITLE
META identity API updates integration

### ISSUE THREAD

**Issue by lukehedger** [meta-network/meta-id-dapp#44]
### Identity
- [x] Update `createIdentity` method: `mutation createIdentity()`
```
mutation CreateIdentity($identity: IdentityInput!) {
  createIdentity(input: $identity) {
    id
    username
    owner
    signature
  }
}

{
  identity: {
    username: 'the-adults',
    owner: '0x932D1f56839B2541bCB876504aAe41E826849Ea3',
    signature: '0x21150570146257b28d3c6ffa598ec4d45ba630e1ff668c439f7bb3c93fbff2471428d4fd4b603595d7b873b2226c7dabe97a54d07848597e171e6e73fb57e9b500',
  }
}
```
- [x] Add `readIdentity` method: `identity()`
```
query readIdentity($filter: IdentityFilter!) {
  identity(filter: $filter) {
    id
    owner
    signature
    username
  }
}

{
  filter: {
    id: '0x...' || 
    username: sha3('xyz.id.meta') ||
    owner: '0x...'
  }
}
```
- [x] Remove `readIdentityById` method
- [x] Remove `readIdentityByOwner` method

### Claim
- [x] Update `createClaim` method: `mutation createClaim()`
```
mutation CreateClaim($claim: ClaimInput!) {
  createClaim(input: $claim) {
    id
    issuer
    subject
    property
    claim
    signature
  }
}

{
  claim: {
    issuer: '0x2787d7568b3de09db05890429d6e47fceeb5eef70a784769ba69d87055f2652c',
    subject: '0x2787d7568b3de09db05890429d6e47fceeb5eef70a784769ba69d87055f2652c',
    property: 'dpid',
    claim: 'DPID:PADPIDA2007050901U|1372985',
    signature: '0xbfc5788e068b73e1f84b867b3e46d63b5819a0ef23daaf031d50eb681a3a66a16768c5ea5f8db1e6c734f458c79d5039a43afa8831222f74b79311cc17c6ac0400',
  }
}
```
- [x] Add `readClaims` method: `claim()`
```
query readIdentity($filter: ClaimFilter!) {
  claim(filter: $filter) {
      id
      issuer
      subject
      property
      claim
      signature
  }
}

{
  filter: {
    issuer: '0x...' ||
    subject: '0x...' ||
    property: '' ||
    claim: '0x...'
  }
}
```
- [x] Remove `readClaimsByIssuer` method
- [x] Remove `readClaimsBySubject` method
