### ISSUE TITLE
Retrieve claims about a META-ID from META Claims Index

### ISSUE THREAD

**Issue by lukehedger** [meta-network/meta-id-dapp#8]
- [x] Add `claim` by **issuer** GraphQL query to the `meta-id` service
- [x] Add `claim` by **subject** GraphQL query to the `meta-id` service
- [x] Add `readClaimsByIssuer` action to `claims` domain (actions/reducer)
- [x] Add `readClaimsBySubject` action to `claims` domain (actions/reducer)
- [x] Add `getClaimsAboutIdentity` selector to `claims` domain
- [x] Add `getClaimsByIdentity` selector to `claims` domain

```
{
  claim (
    subject:<subjectid>,
    issuer:<issuerid>,
    claim:<claim>,
    signature:<signature>
  ) {
    issuer
    subject
    claim
    signature
  }
}
```
